name: Python Matrix Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: pytest -q
      - name: Upload junit
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-reports-${{ matrix.python-version }}
          path: reports/
